"use client"
// import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { AuthContextProvider } from "./context/AuthContext"
import Navbar from "./components/Navbar/Navbar"

const inter = Inter({ subsets: ["latin"] })

import styles from "./layout.module.css"

import { useStore } from "./store"

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const isMenuOpen = useStore((state) => state.isMenuOpen)

  return (
    <html lang="en" className={isMenuOpen ? styles.locked : ""}>
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
